"""init migrate

Revision ID: df6f75da5282
Revises: 
Create Date: 2026-10-06 11:06:24.556945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6f75da5282'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_agg',
    sa.Column('warehouse', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('warehouse', 'sku')
    )
    op.create_table('stock_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('warehouse', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('receipt', 'issue', name='event_type'), nullable=False),
    sa.Column('applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name='qty_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_events_unapplied', 'stock_events', ['warehouse', 'sku'], unique=False, postgresql_where=sa.text('NOT applied'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_events_unapplied', table_name='stock_events', postgresql_where=sa.text('NOT applied'))
    op.drop_table('stock_events')
    op.drop_table('stock_agg')
    # ### end Alembic commands ###
